"""Narrow structural capabilities exposed by authoritative Store adapters."""

from __future__ import annotations

from typing import Protocol

from aigineering.protocol.runtime_record import RuntimeRecord
from aigineering.protocol.types import Asset, Contract, TraceEntry


class AssetReader(Protocol):
    """Read-only access to materialized Assets and their graph records."""

    def get_asset(self, asset_id: str) -> Asset | None: ...
    def get_assets_by_name(self, name: str) -> list[Asset]: ...
    def has_asset_named(self, name: str) -> bool: ...
    def get_all_assets(self) -> list[Asset]: ...
    def get_assets_by_contract(self, contract_id: str) -> list[Asset]: ...
    def get_assets_by_definition(self, def_hash: str) -> list[Asset]: ...
    def get_latest_asset(self, def_hash: str) -> Asset | None: ...
    def get_content_objects(self) -> list[dict]: ...
    def get_asset_definitions(self) -> list[dict]: ...
    def get_definition_content_assertions(
        self, *, definition_id: str = "", content_id: str = ""
    ) -> list[dict]: ...
    def get_claims_by_definition(self, definition_hash: str) -> list: ...
    def get_claims_for_asset(self, asset_id: str) -> list: ...
    def get_claims_for_replacement_asset(self, asset_id: str) -> list: ...


class ContractReader(Protocol):
    """Read-only access to immutable Contracts and projection indexes."""

    def get_contract(self, contract_id: str) -> Contract | None: ...
    def get_all_contracts(self) -> list[Contract]: ...
    def get_contracts_waiting_for(self, asset_name: str) -> list[str]: ...
    def get_contracts_declaring_output(self, asset_name: str) -> list[str]: ...
    def projection_index_digest(self) -> str: ...


class RuntimeRecordReader(Protocol):
    """Read-only access to the durable runtime fact log."""

    def get_runtime_record(self, record_id: str) -> RuntimeRecord | None: ...
    def scan_runtime_records(
        self, *, after_revision: int = 0, record_type: str | None = None
    ) -> list[tuple[int, RuntimeRecord]]: ...
    def get_runtime_revision(self) -> int: ...


class TraceReader(Protocol):
    """Read-only access to immutable trace entries."""

    def get_by_contract(self, contract_id: str) -> list[TraceEntry]: ...
    def get_by_event_type(self, event_type: str) -> list[TraceEntry]: ...
    def get_all(self) -> list[TraceEntry]: ...
    def get_reverse_lineage(self, asset_id: str) -> list[TraceEntry]: ...


class CandidateCommitStore(AssetReader, ContractReader, RuntimeRecordReader, Protocol):
    """The single transactional Candidate commitment capability."""

    def commit_ingress_batch(self, *args, **kwargs) -> tuple[tuple, tuple]: ...


class WorkerClaimStore(Protocol):
    """Transactional worker registration, claim, and failure capabilities."""

    def get_worker_registration(self, worker_id: str): ...
    def get_worker_registrations(self) -> list: ...
    def get_claim(self, contract_id: str) -> dict | None: ...
    def claim_contract(self, *args, **kwargs) -> dict | None: ...
    def renew_claim(self, *args, **kwargs) -> dict | None: ...
    def commit_worker_invocation_failure(self, *args, **kwargs) -> bool: ...
    def commit_claim_expiration(self, *args, **kwargs) -> bool: ...
